---
deployment:
  tasks:
    - export DEPLOYPATH=/home/violacom/public_html/app/2020_vimoney
    
    # copy content from repository to deploy folder
    - /bin/cp -r ./* $DEPLOYPATH
    
    # move content from public folder to root of deployed folder
    - /bin/mv -r  $DEPLOYPATH/public/* $DEPLOYPATH